name: 'CF Push cli8'
description: Push an application to a Cloud Foundry
inputs:
  manifest:
    description: The path to your CF application manifest
    required: true
  appdir:
    description: Set this parameter if you want to switch the working dir to push an app
    required: true
  API:
    description: The Cloud Foundry API endpoint
    required: true
  CF_USERNAME:
    description: Your Cloud Foundry authentication username (or email address)
    required: true
  CF_PASSWORD:
    description: Your Cloud Foundry authentication password
    required: true
  CF_ORG:
    description: The name of the Cloud Foundry organization in which to deploy
    required: true
  CF_SPACE:
    description: The name of the Cloud Foundry space in which to deploy
    required: true
  validate:
    description: Whether or not to validate the CF API's TLS certificate
    required: false
    default: true
  debug:
    description: Debug your deploy dir to list all folders
    required: false
    default: false
  command:
    description: "Command to run using CF CLI"
    required: true


runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.command }}
